language: android

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

jdk:
  - oraclejdk8

env:
  global:
    - TERM=dumb
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-29
    - extra
    - addon

  licenses:
    - 'android-sdk-license-.+'

install: /bin/true

script: ./gradlew build

deploy:
  - provider: script
    script: scripts/bintrayUpload.sh
    skip_cleanup: true
    on:
      tags: true
