language: android

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

jdk:
  - oraclejdk8

env:
  global:
    - TERM=dumb
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"

android:
  components:
    - build-tools-25.0.0
    - android-23
    - platform-tools
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - 'android-sdk-license-.+'

install: /bin/true

script: ./gradlew build

deploy:
  - provider: script
    script: scripts/bintrayUpload.sh
    skip_cleanup: true
    on:
      tags: true
